<?php
$title_number_t='Номер';
$title_num_t='№';
$title_type='Тип';
$title_class='Вид';
$title_time='Время';
$title_adres='Адрес';
$title_phone='Телефон';
$title_status='Статус';
$title_complete='Выполнил';
$title_state='СМС';
$title_description='Описание';
$title_tarif='Тариф';
$title_date='Дата';
$title_date_check='Выполнена';
$title_search='Поиск';
$title_profiles='Профили';
$title_create_user_tickets='Добавил(а)'
?>